// Code generated by protoc-gen-go.
// source: object.proto
// DO NOT EDIT!

/*
Package object is a generated protocol buffer package.

It is generated from these files:
	object.proto

It has these top-level messages:
	ObjectIdentifier
	ObjectResponse
*/
package object

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ObjectIdentifier struct {
	Account   string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Container string `protobuf:"bytes,2,opt,name=container" json:"container,omitempty"`
	Path      string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
}

func (m *ObjectIdentifier) Reset()                    { *m = ObjectIdentifier{} }
func (m *ObjectIdentifier) String() string            { return proto.CompactTextString(m) }
func (*ObjectIdentifier) ProtoMessage()               {}
func (*ObjectIdentifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ObjectIdentifier) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ObjectIdentifier) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *ObjectIdentifier) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ObjectResponse struct {
	Type    string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Mtime   string `protobuf:"bytes,2,opt,name=mtime" json:"mtime,omitempty"`
	Etag    string `protobuf:"bytes,3,opt,name=etag" json:"etag,omitempty"`
	Content []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *ObjectResponse) Reset()                    { *m = ObjectResponse{} }
func (m *ObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*ObjectResponse) ProtoMessage()               {}
func (*ObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ObjectResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ObjectResponse) GetMtime() string {
	if m != nil {
		return m.Mtime
	}
	return ""
}

func (m *ObjectResponse) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *ObjectResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*ObjectIdentifier)(nil), "object.ObjectIdentifier")
	proto.RegisterType((*ObjectResponse)(nil), "object.ObjectResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ObjectAccessor service

type ObjectAccessorClient interface {
	GetObject(ctx context.Context, in *ObjectIdentifier, opts ...grpc.CallOption) (*ObjectResponse, error)
	GetObjectStream(ctx context.Context, opts ...grpc.CallOption) (ObjectAccessor_GetObjectStreamClient, error)
}

type objectAccessorClient struct {
	cc *grpc.ClientConn
}

func NewObjectAccessorClient(cc *grpc.ClientConn) ObjectAccessorClient {
	return &objectAccessorClient{cc}
}

func (c *objectAccessorClient) GetObject(ctx context.Context, in *ObjectIdentifier, opts ...grpc.CallOption) (*ObjectResponse, error) {
	out := new(ObjectResponse)
	err := grpc.Invoke(ctx, "/object.ObjectAccessor/GetObject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectAccessorClient) GetObjectStream(ctx context.Context, opts ...grpc.CallOption) (ObjectAccessor_GetObjectStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ObjectAccessor_serviceDesc.Streams[0], c.cc, "/object.ObjectAccessor/GetObjectStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &objectAccessorGetObjectStreamClient{stream}
	return x, nil
}

type ObjectAccessor_GetObjectStreamClient interface {
	Send(*ObjectIdentifier) error
	Recv() (*ObjectResponse, error)
	grpc.ClientStream
}

type objectAccessorGetObjectStreamClient struct {
	grpc.ClientStream
}

func (x *objectAccessorGetObjectStreamClient) Send(m *ObjectIdentifier) error {
	return x.ClientStream.SendMsg(m)
}

func (x *objectAccessorGetObjectStreamClient) Recv() (*ObjectResponse, error) {
	m := new(ObjectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ObjectAccessor service

type ObjectAccessorServer interface {
	GetObject(context.Context, *ObjectIdentifier) (*ObjectResponse, error)
	GetObjectStream(ObjectAccessor_GetObjectStreamServer) error
}

func RegisterObjectAccessorServer(s *grpc.Server, srv ObjectAccessorServer) {
	s.RegisterService(&_ObjectAccessor_serviceDesc, srv)
}

func _ObjectAccessor_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectAccessorServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object.ObjectAccessor/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectAccessorServer).GetObject(ctx, req.(*ObjectIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectAccessor_GetObjectStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObjectAccessorServer).GetObjectStream(&objectAccessorGetObjectStreamServer{stream})
}

type ObjectAccessor_GetObjectStreamServer interface {
	Send(*ObjectResponse) error
	Recv() (*ObjectIdentifier, error)
	grpc.ServerStream
}

type objectAccessorGetObjectStreamServer struct {
	grpc.ServerStream
}

func (x *objectAccessorGetObjectStreamServer) Send(m *ObjectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *objectAccessorGetObjectStreamServer) Recv() (*ObjectIdentifier, error) {
	m := new(ObjectIdentifier)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ObjectAccessor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "object.ObjectAccessor",
	HandlerType: (*ObjectAccessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetObject",
			Handler:    _ObjectAccessor_GetObject_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetObjectStream",
			Handler:       _ObjectAccessor_GetObjectStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "object.proto",
}

func init() { proto.RegisterFile("object.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x90, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0x8d, 0x9e, 0x27, 0x3b, 0x1c, 0x2a, 0x83, 0x48, 0x10, 0x8b, 0x63, 0xab, 0xad, 0x0e,
	0xd1, 0x07, 0x10, 0x2b, 0xd9, 0x4a, 0x58, 0x7b, 0x21, 0x1b, 0x47, 0x37, 0xc2, 0x26, 0x21, 0x19,
	0x0b, 0xdf, 0xc5, 0x87, 0x95, 0x24, 0x1b, 0x45, 0x4b, 0xbb, 0xef, 0x9b, 0x6f, 0xf8, 0xcd, 0x1f,
	0xd8, 0xb8, 0xf1, 0x8d, 0x34, 0xef, 0x7c, 0x70, 0xec, 0x70, 0x5d, 0x5c, 0xfb, 0x04, 0xa7, 0x0f,
	0x59, 0xf5, 0xcf, 0x64, 0xd9, 0xbc, 0x18, 0x0a, 0x28, 0xe1, 0x48, 0x69, 0xed, 0xde, 0x2d, 0x4b,
	0xb1, 0x15, 0x5d, 0x33, 0x54, 0x8b, 0x97, 0xd0, 0x68, 0x67, 0x59, 0x19, 0x4b, 0x41, 0xee, 0xe7,
	0xec, 0xa7, 0x80, 0x08, 0x2b, 0xaf, 0x78, 0x92, 0x07, 0x39, 0xc8, 0xba, 0x9d, 0xe0, 0xb8, 0xf0,
	0x07, 0x8a, 0xde, 0xd9, 0x48, 0xa9, 0x8b, 0x3f, 0x3c, 0x2d, 0xe8, 0xac, 0xf1, 0x0c, 0x0e, 0x67,
	0x36, 0x33, 0x2d, 0xcc, 0x62, 0x52, 0x27, 0xb1, 0x7a, 0xad, 0xbc, 0xa4, 0xd3, 0x6e, 0x69, 0x20,
	0x59, 0x96, 0xab, 0xad, 0xe8, 0x36, 0x43, 0xb5, 0xd7, 0x9f, 0xa2, 0x8e, 0xba, 0xd3, 0x9a, 0x62,
	0x74, 0x01, 0x6f, 0xa1, 0xb9, 0x27, 0x2e, 0x45, 0x94, 0xbb, 0xe5, 0x01, 0x7f, 0xef, 0xbd, 0x38,
	0xff, 0x9d, 0xd4, 0x4d, 0xdb, 0x3d, 0xec, 0xe1, 0xe4, 0x1b, 0xf0, 0xc8, 0x81, 0xd4, 0xfc, 0x1f,
	0x4c, 0x27, 0xae, 0xc4, 0xb8, 0xce, 0x7f, 0xbf, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x80,
	0x7b, 0x40, 0x87, 0x01, 0x00, 0x00,
}
